/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/accounts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Accounts */
        get: operations["list_accounts_accounts_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/accounts/{account_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Rename Account */
        patch: operations["rename_account_accounts__account_id__patch"];
        trace?: never;
    };
    "/categories": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Categories */
        get: operations["list_categories_categories_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/categorize/run": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Run */
        post: operations["run_categorize_run_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/dashboard/overview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Overview */
        get: operations["overview_dashboard_overview_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/dashboard/subscriptions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Subscriptions */
        get: operations["subscriptions_dashboard_subscriptions_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/imports": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Imports */
        get: operations["list_imports_imports_get"];
        put?: never;
        /** Create Import */
        post: operations["create_import_imports_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/merchants": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Merchants */
        get: operations["list_merchants_merchants_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/merchants/{merchant_id}/review": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Review Merchant */
        post: operations["review_merchant_merchants__merchant_id__review_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/merchants/{merchant_id}/default": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Clear Default */
        delete: operations["clear_default_merchants__merchant_id__default_delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/merchants/{merchant_id}/dismiss-merge": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Dismiss */
        post: operations["dismiss_merchants__merchant_id__dismiss_merge_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/review": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Review */
        get: operations["get_review_review_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/review/count": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Review Count */
        get: operations["get_review_count_review_count_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/spending/detail": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Detail */
        get: operations["detail_spending_detail_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/transactions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Transactions */
        get: operations["list_transactions_transactions_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/transactions/{transaction_id}/label": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Label */
        post: operations["label_transactions__transaction_id__label_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/transactions/{transaction_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update Note */
        patch: operations["update_note_transactions__transaction_id__patch"];
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** Account */
        Account: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Bank */
            bank: string;
            /** Iban Last4 */
            iban_last4: string;
            /** Name */
            name: string;
            /** Currency */
            currency: string;
        };
        /** AccountUpdate */
        AccountUpdate: {
            /** Name */
            name: string;
        };
        /** Body_create_import_imports_post */
        Body_create_import_imports_post: {
            /** File */
            file: string;
        };
        /** BreakdownRow */
        BreakdownRow: {
            /** Key */
            key: string;
            /** Label */
            label: string | null;
            /** Level1 */
            level1: string | null;
            /** Category Slug */
            category_slug: string | null;
            /** Merchant Id */
            merchant_id: string | null;
            /** Amount */
            amount: string;
            /** Share */
            share: number;
            /** Previous */
            previous: string | null;
            /** Count */
            count: number;
            /**
             * Folded
             * @default 0
             */
            folded: number;
        };
        /** CategoryOut */
        CategoryOut: {
            /** Slug */
            slug: string;
            /** Tx Type */
            tx_type: string;
            /** Level1 */
            level1: string;
        };
        /** CategoryScore */
        CategoryScore: {
            /** Slug */
            slug: string;
            /** Confidence */
            confidence: number;
        };
        /** ConfirmMerchant */
        ConfirmMerchant: {
            /** Category Slug */
            category_slug: string;
            /** Is Subscription */
            is_subscription: boolean;
            /** Name */
            name?: string | null;
            /** Merge Into Id */
            merge_into_id?: string | null;
        };
        /** Cumulative */
        Cumulative: {
            /** Current */
            current: components["schemas"]["CumulativePoint"][];
            /** Previous */
            previous: components["schemas"]["CumulativePoint"][] | null;
        };
        /** CumulativePoint */
        CumulativePoint: {
            /** Day */
            day: number;
            /**
             * Date
             * Format: date
             */
            date: string;
            /** Total */
            total: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** ImportRecord */
        ImportRecord: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Account Id
             * Format: uuid
             */
            account_id: string;
            /** Account Name */
            account_name: string;
            /** Filename */
            filename: string;
            /** Period Start */
            period_start: string | null;
            /** Period End */
            period_end: string | null;
            /** Rows Total */
            rows_total: number;
            /** Rows New */
            rows_new: number;
            /** Rows Duplicate */
            rows_duplicate: number;
            /**
             * Imported At
             * Format: date-time
             */
            imported_at: string;
        };
        /** ImportSummary */
        ImportSummary: {
            /**
             * Import Id
             * Format: uuid
             */
            import_id: string;
            /**
             * Account Id
             * Format: uuid
             */
            account_id: string;
            /**
             * Bank
             * @enum {string}
             */
            bank: "bbva" | "caixabank";
            /** Iban Last4 */
            iban_last4: string;
            /** Filename */
            filename: string;
            /** Rows Total */
            rows_total: number;
            /** Rows New */
            rows_new: number;
            /** Rows Duplicate */
            rows_duplicate: number;
        };
        /** LabelTransaction */
        LabelTransaction: {
            /** Category Slug */
            category_slug: string;
            /**
             * Is Subscription
             * @default false
             */
            is_subscription: boolean;
            /** Merchant Id */
            merchant_id?: string | null;
            /** New Merchant Name */
            new_merchant_name?: string | null;
        };
        /** MerchantOut */
        MerchantOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
        };
        /** MergeSuggestion */
        MergeSuggestion: {
            /**
             * Merchant Id
             * Format: uuid
             */
            merchant_id: string;
            /** Name */
            name: string;
            /** Confidence */
            confidence: number;
        };
        /** MonthPoint */
        MonthPoint: {
            /** Month */
            month: string;
            /** Has Data */
            has_data: boolean;
            /** Income */
            income: string | null;
            /** Expenses */
            expenses: string | null;
            /** Savings */
            savings: string | null;
        };
        /** NoteUpdate */
        NoteUpdate: {
            /** Note */
            note?: string | null;
        };
        /** Overview */
        Overview: {
            period: components["schemas"]["PeriodOut"];
            kpis: components["schemas"]["Totals"];
            previous_kpis: components["schemas"]["Totals"] | null;
            cumulative: components["schemas"]["Cumulative"];
            /** Months */
            months: components["schemas"]["MonthPoint"][];
            /** By Group */
            by_group: components["schemas"]["BreakdownRow"][];
            /** By Category */
            by_category: components["schemas"]["BreakdownRow"][];
            /** By Merchant */
            by_merchant: components["schemas"]["BreakdownRow"][];
            /** Group Slots */
            group_slots: {
                [key: string]: number;
            };
            subscriptions: components["schemas"]["SubscriptionsSummary"];
        };
        /** PeriodOut */
        PeriodOut: {
            /**
             * Name
             * @enum {string}
             */
            name: "month" | "last_3_months" | "ytd" | "last_12_months" | "custom";
            /**
             * Start
             * Format: date
             */
            start: string;
            /**
             * End
             * Format: date
             */
            end: string;
            /**
             * Previous Start
             * Format: date
             */
            previous_start: string;
            /**
             * Previous End
             * Format: date
             */
            previous_end: string;
            /** Has Previous */
            has_previous: boolean;
            /** Latest Day */
            latest_day: string | null;
        };
        /** ReviewCount */
        ReviewCount: {
            /** Pending */
            pending: number;
            /** Uncategorized */
            uncategorized: number;
        };
        /** ReviewItem */
        ReviewItem: {
            /** Key */
            key: string;
            /**
             * Kind
             * @enum {string}
             */
            kind: "merchant" | "transaction";
            merchant: components["schemas"]["MerchantOut"] | null;
            /** Transactions */
            transactions: components["schemas"]["ReviewTransaction"][];
            /** Count */
            count: number;
            /** Total */
            total: string;
            suggestion: components["schemas"]["Suggestion"];
            merge: components["schemas"]["MergeSuggestion"] | null;
        };
        /** ReviewTransaction */
        ReviewTransaction: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Booked At
             * Format: date
             */
            booked_at: string;
            /** Amount */
            amount: string;
            /** Description Raw */
            description_raw: string;
            /** Account Name */
            account_name: string;
        };
        /** RunQueued */
        RunQueued: {
            /**
             * Status
             * @constant
             */
            status: "queued";
        };
        /** ScopeMonth */
        ScopeMonth: {
            /** Month */
            month: string;
            /** Has Data */
            has_data: boolean;
            /** Total */
            total: string | null;
            /** By Child */
            by_child: {
                [key: string]: string;
            };
        };
        /** SpendingDetail */
        SpendingDetail: {
            period: components["schemas"]["PeriodOut"];
            /**
             * Type
             * @enum {string}
             */
            type: "expense" | "income";
            /** Level1 */
            level1: string | null;
            /** Category */
            category: string | null;
            /** Merchant Id */
            merchant_id: string | null;
            /** Merchant Name */
            merchant_name: string | null;
            /** Total */
            total: string;
            /** Previous Total */
            previous_total: string | null;
            /** Count */
            count: number;
            /** Months */
            months: components["schemas"]["ScopeMonth"][];
            /** Child Keys */
            child_keys: string[];
            /** Children */
            children: components["schemas"]["BreakdownRow"][];
            /** Top Merchants */
            top_merchants: components["schemas"]["BreakdownRow"][];
            cumulative: components["schemas"]["Cumulative"];
            /** Latest */
            latest: components["schemas"]["Transaction"][];
        };
        /** SubscriptionOut */
        SubscriptionOut: {
            /**
             * Merchant Id
             * Format: uuid
             */
            merchant_id: string;
            /** Merchant Name */
            merchant_name: string;
            /**
             * Cadence
             * @enum {string}
             */
            cadence: "monthly" | "yearly";
            /** Typical Amount */
            typical_amount: string;
            /** Monthly Equivalent */
            monthly_equivalent: string;
            /**
             * Last Charge
             * Format: date
             */
            last_charge: string;
            /** Charges */
            charges: number;
        };
        /** Subscriptions */
        Subscriptions: {
            /** Items */
            items: components["schemas"]["SubscriptionOut"][];
            /** Monthly Total */
            monthly_total: string;
            /** Yearly Total */
            yearly_total: string;
        };
        /** SubscriptionsSummary */
        SubscriptionsSummary: {
            /** Count */
            count: number;
            /** Monthly Total */
            monthly_total: string;
            /** Yearly Total */
            yearly_total: string;
        };
        /** Suggestion */
        Suggestion: {
            /** Category Slug */
            category_slug: string | null;
            /** Level1 */
            level1: string | null;
            /** Confidence */
            confidence: number | null;
            /** Is Subscription */
            is_subscription: boolean;
            /** Top */
            top: components["schemas"]["CategoryScore"][];
        };
        /** Totals */
        Totals: {
            /** Income */
            income: string;
            /** Expenses */
            expenses: string;
            /** Savings */
            savings: string;
            /** Savings Rate */
            savings_rate: number | null;
        };
        /** Transaction */
        Transaction: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Booked At
             * Format: date
             */
            booked_at: string;
            /**
             * Account Id
             * Format: uuid
             */
            account_id: string;
            /** Account Name */
            account_name: string;
            /** Amount */
            amount: string;
            /** Description Raw */
            description_raw: string;
            /** Bank Merchant Text */
            bank_merchant_text: string | null;
            /** Merchant Id */
            merchant_id: string | null;
            /** Merchant Name */
            merchant_name: string | null;
            /** Tx Type */
            tx_type: string;
            /** Category Slug */
            category_slug: string | null;
            /** Level1 */
            level1: string | null;
            /** Category Source */
            category_source: string;
            /** Is Subscription */
            is_subscription: boolean;
            /** Needs Review */
            needs_review: boolean;
            /** Note */
            note: string | null;
            /** Transfer Pair Id */
            transfer_pair_id: string | null;
        };
        /** TransactionPage */
        TransactionPage: {
            period: components["schemas"]["PeriodOut"];
            /** Items */
            items: components["schemas"]["Transaction"][];
            /** Next Cursor */
            next_cursor: string | null;
            /** Count */
            count: number;
            /** Money In */
            money_in: string;
            /** Money Out */
            money_out: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    list_accounts_accounts_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Account"][];
                };
            };
        };
    };
    rename_account_accounts__account_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                account_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AccountUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Account"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_categories_categories_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CategoryOut"][];
                };
            };
        };
    };
    run_categorize_run_post: {
        parameters: {
            query?: {
                all?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunQueued"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    overview_dashboard_overview_get: {
        parameters: {
            query?: {
                period?: "month" | "last_3_months" | "ytd" | "last_12_months" | "custom";
                month?: string | null;
                start?: string | null;
                end?: string | null;
                account_id?: string[];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Overview"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    subscriptions_dashboard_subscriptions_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Subscriptions"];
                };
            };
        };
    };
    list_imports_imports_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ImportRecord"][];
                };
            };
        };
    };
    create_import_imports_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_create_import_imports_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ImportSummary"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_merchants_merchants_get: {
        parameters: {
            query?: {
                q?: string | null;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MerchantOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    review_merchant_merchants__merchant_id__review_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                merchant_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ConfirmMerchant"];
            };
        };
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    clear_default_merchants__merchant_id__default_delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                merchant_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    dismiss_merchants__merchant_id__dismiss_merge_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                merchant_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_review_review_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReviewItem"][];
                };
            };
        };
    };
    get_review_count_review_count_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReviewCount"];
                };
            };
        };
    };
    detail_spending_detail_get: {
        parameters: {
            query?: {
                type?: "expense" | "income";
                level1?: string | null;
                category?: string | null;
                merchant_id?: string | null;
                period?: "month" | "last_3_months" | "ytd" | "last_12_months" | "custom";
                month?: string | null;
                start?: string | null;
                end?: string | null;
                account_id?: string[];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SpendingDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_transactions_transactions_get: {
        parameters: {
            query?: {
                q?: string | null;
                tx_type?: ("expense" | "income" | "transfer") | null;
                level1?: string | null;
                category?: string | null;
                merchant_id?: string | null;
                is_subscription?: boolean | null;
                category_source?: ("rule" | "merchant" | "jev" | "user" | "none") | null;
                needs_review?: boolean | null;
                saved?: ("unpaired_own" | "refunds") | null;
                cursor?: string | null;
                limit?: number;
                period?: "month" | "last_3_months" | "ytd" | "last_12_months" | "custom";
                month?: string | null;
                start?: string | null;
                end?: string | null;
                account_id?: string[];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TransactionPage"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    label_transactions__transaction_id__label_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                transaction_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LabelTransaction"];
            };
        };
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_note_transactions__transaction_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                transaction_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["NoteUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
}
